CREATE SCHEMA IF NOT EXISTS pokemon;

CREATE TABLE IF NOT EXISTS pokemon.stg_pokemon_bravo (
    nome CHARACTER VARYING(200) NOT NULL,
    numero INTEGER NOT NULL,
    ranking INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS pokemon.stg_pokemon_api (
    tipo CHARACTER VARYING(200) NOT NULL,
    habilidades CHARACTER VARYING(200) NOT NULL,
    pokedex INTEGER NOT NULL,
    geracao CHARACTER VARYING(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS pokemon.fato_pokemon (
    pokedex INTEGER PRIMARY KEY NOT NULL,
    nome CHARACTER VARYING(200) NOT NULL,
    tipo CHARACTER VARYING(200) NOT NULL,
    habilidades CHARACTER VARYING(200) NOT NULL,
    geracao CHARACTER VARYING(200) NOT NULL,
    ranking INTEGER NOT NULL
);
